on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Setup r2u
        uses: eddelbuettel/github-actions/r2u-setup@master

      - name: Package Dependencies
        run: Rscript -e 'install.packages(c("mapme.biodiversity", "leaflet.extras", "leaflet", "ggplot2", "sf", "exactextractr", "landscapemetrics", "plotly"))'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}